offline:
  default: Hah칩! Nincs neted! 游땭
try_connect:
  default: Kapcsol칩d치si k칤s칠rlet...
waiting:
  default: Hah칩! Nincs neted! 游땭
wait_in_connect:
  default: Kapcsol칩d치s
wait_in_seconds:
  default: mp-n bel칲l...
wait_in_minutes:
  default: percen bel칲l...
wait_in_hours:
  default: 칩r치n bel칲l...
fail_connect:
  default: A kapcsol칩d치s sikertelen...
online:
  default: Ezazz, 칰jra online! 游꿀
