offline:
  default: Hah칩! Nincs neted! 游땭
tryconnect:
  default: Kapcsol칩d치si k칤s칠rlet...
waiting:
  default: Hah칩! Nincs neted! 游땭
waitconnect:
  default: Kapcsol칩d치s
waitinsecond:
  default: mp-n bel칲l...
waitinminute:
  default: percen bel칲l...
waitinhour:
  default: 칩r치n bel칲l...
failconnect:
  default: A kapcsol칩d치s sikertelen...
online:
  default: Ezazz, 칰jra online! 游꿀
